### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hardikdava** [AyushExel/trolo#15]
Hello @AyushExel , congratulations on starting new project. Here are some suggestions that can remove some overhead in development. 

- Use supervision to enable different visualization
- Add examples scripts for different tasks prefer colab notebook
- Pretrained models are not auto downloading

**Comment by AyushExel** [comment]
Yes those are good suggestions. 
* Sure, would you like to contribute for 1?
* Yes, I've added an issue to tack examples
* Can you provide a reproducible script to show auto-download is not working?

**Comment by hardikdava** [comment]
@AyushExel sure, I will start with first one after you finish with lint PR.

**Comment by hardikdava** [comment]
@AyushExel Please update todos. So contributors will know pending tasks.

**Comment by AyushExel** [comment]
Thanks will do. Would you like to be a maintainer ?

**Comment by senhorinfinito** [comment]
1.  Is there plan for having docker support as well. ?

**Comment by AyushExel** [comment]
@senhorinfinito sure that sounds like a good idea

**Comment by hardikdava** [comment]
> Thanks will do. Would you like to be a maintainer ?

@AyushExel thank you for your offer. But I generally managed to contribute only during weekends due to my other job. I will keep contribute in either ways.

**Comment by AyushExel** [comment]
@hardikdava yeah that is fine, I'll make you admin so atleast you can merge PRs and close issues whenever you got time

**Comment by hardikdava** [comment]
@AyushExel Thank you.

**Comment by AyushExel** [comment]
@hardikdava invited you as a collaborator
