### ISSUE TITLE
Docs using mkdocs

### ISSUE THREAD

**Issue by senhorinfinito** [AyushExel/trolo#19]
Hey @AyushExel . 

instead of Docusaurus, can MkDocs work?

**Comment by AyushExel** [comment]
There are many limitations in mkdocs when you want to customize. Are there any special features you'd like from mkdocs?

**Comment by senhorinfinito** [comment]
There is no as such, but in design wise it looks good and (material)[https://squidfunk.github.io/mkdocs-material/]. This is nice.

**Comment by AyushExel** [comment]
Yeah I haven't spent much time on theming so that's definitely one place to do something. But I think it'll be much easier to apply style to docusaurus as it is basically a react app

**Comment by senhorinfinito** [comment]
understood. I'll close this comment.
