### ISSUE TITLE
letterbox input image 

### ISSUE THREAD

**Issue by hardikdava** [AyushExel/trolo#20]
Input image is directly resized to (640,640) but it should rather letterbox in order to get maximum accuracy of prediction

**Comment by AyushExel** [comment]
Yeah good catch. I wanted to do this before making it public but slipped my mind

**Comment by hardikdava** [comment]
@AyushExel A question: letterbox should be with torch or numpy works?

**Comment by AyushExel** [comment]
hmm either way CUDA acceleration won't be used right?

**Comment by hardikdava** [comment]
@AyushExel I don't think so.

**Comment by AyushExel** [comment]
okay then I think either works

**Comment by hardikdava** [comment]
@AyushExel We can directly use it from supervision, that will be faster option if you don't mind it.

**Comment by AyushExel** [comment]
Sure
