### ISSUE TITLE
DDP for training is causing issues

### ISSUE THREAD

**Issue by quinnZE** [AyushExel/trolo#44]
### Search before asking

- [X] I have searched the Trolo [issues](https://github.com/AyushExel/trolo/issues) and found no similar bug report.

### Bug

It seems that DDP for trolo train may be executing too soon in the training script. When I begin training from DDP, it begins to download the coco zip file on the second instance while the first is still prompting me about WandB. After completing the prompt, the first instance then begins downloading a duplicate zip. 
![image](https://github.com/user-attachments/assets/ed066bdd-38f5-4bd7-abaf-c0ee375bdede)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by its-the-ging** [comment]
Issue can be fixed by modifying `BaseTrainer` so that `check_and_download_dataset()` is called in `train()` prior to line 465 and not in `_setup()`. See below, I do not have access rights to make PR.
![image](https://github.com/user-attachments/assets/49ae434e-7ccf-49a5-8cf4-fa244d73df61)

**Comment by AyushExel** [comment]
Oh you can make PRs by forking the repo, it is available to all users. Can you try once? Thanks!

**Comment by its-the-ging** [comment]
PR submitted!
