### ISSUE TITLE
Add better logging

### ISSUE THREAD

**Issue by AyushExel** [AyushExel/trolo#7]
While implementing this repo, I used print statements everywhere. It'd be nice to setup a logging module replace print statments

**Comment by senhorinfinito** [comment]
Hey @AyushExel  
I'll take this up.   Do you have any  primary requirements ?

**Comment by AyushExel** [comment]
No specific requirements just global logging module

**Comment by senhorinfinito** [comment]
Hey @AyushExel , Which one you recommend to moving ahead with for logging. 

Logging  1 
![image](https://github.com/user-attachments/assets/40a29ab5-6931-4459-9dc6-687a4d97e7ad)

Logging 2 
![image](https://github.com/user-attachments/assets/0dc2f3f6-554c-43b3-9789-05a5e6f30c6a)

In my opinion logging one will be better.

**Comment by AyushExel** [comment]
Yup 1 sounds good. Thanks!

**Comment by senhorinfinito** [comment]
#24  created the PR

**Comment by senhorinfinito** [comment]
Please close this if you happy with the above PR.

**Comment by AyushExel** [comment]
sure thanks!
